### ISSUE TITLE
2.0.4-v.3 - pop-up window of bottom person in Family Navigator not fully displayed

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#11]
The pop-up window of the bottom person in the Family Navigator is not fully displayed:
![afbeelding](https://user-images.githubusercontent.com/46184729/87849981-fe269580-c8ec-11ea-9500-3a84ded62424.png)

**Tested configuration**

- webtrees v2.0.6 with modules:
- + Rural Theme 2.0.4-v.3
- + Tree View Full Screen v0.8
- + Vesta Classic Look & Feel v2.0.6.2.0
- + Vesta Extended Relationships v2.0.6.2.0
- + webtrees-fan-chart v2.0.3
- OS: Win 10 Home x64 v1909
- Device: desktop
- Browsers: Edge v84.0.522.40 and Firefox v78.0.2

**Comment by jon48** [comment]
Hello,
This does not seem specific to the Rural theme, as I can see it on other standard themes as well, and comes down to a bit of a limitation in Boostrap when associating dropdowns with enclosing divs.

There are suggestions to work around it, and I have tried implementing it (hoping there are no other side effects, as I cannot make it specific to the Family Navigator.
You can try with the [file attached](https://github.com/jon48/webtrees-theme-rural/files/4942900/rural.min.css.zip).

**Comment by TheDutchJewel** [comment]
Thank you very much for the solution: it works fine!
