### ISSUE TITLE
2.0.4-v.3 - Family navigator > family: pedigree boxes have different dimensions 

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#12]
After updating webtrees from 2.0.6 to 2.0.7, and click on a family in the Family navigator, the pedigree boxes have different dimensions:
![afbeelding](https://user-images.githubusercontent.com/46184729/88660332-cf6fa280-d0d6-11ea-994c-64c29274ce9d.png)

Check also [this issue](https://github.com/jon48/webtrees-theme-rural/issues/1): 

**Tested configuration**

- webtrees v2.0.7 with modules:
- + Rural Theme 2.0.4-v.3
- + Tree View Full Screen v0.8
- + Vesta Classic Look & Feel v2.0.7.0.0
- + Vesta Extended Relationships v2.0.7.0.0
- + webtrees-fan-chart v2.0.3
- OS: Win 10 Home x64 v2004
- Device: desktop
- Screen resolution: 1920x1080
- Local web server: XAMPP portable x64 v7.3.20
- Browsers: Edge v84.0.522.44 and Firefox v78.0.2

**Comment by jon48** [comment]
This is a change introduced in the main webtrees classes, which requires an update of the theme.
Depending on your expected stability of the theme, I would suggest waiting for my confirmation on the forum or on the release page of the compatibility of the theme with a new version of webtrees before upgrading it, or raising the issue. 

I have just released 2.0.7-v.1 that should address the issue.
