### ISSUE TITLE
missing hamburger menu icons

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#13]
![missing hamburger on small screen](https://user-images.githubusercontent.com/6124739/95618475-6bba0c00-0a6d-11eb-898e-3ab9ef463f05.jpg)

**Comment by arbor95** [comment]
is needed see:
![missing theme selection on small screen](https://user-images.githubusercontent.com/6124739/95618676-c6536800-0a6d-11eb-9d70-335ec305dccf.jpg)

compare on large screen
![existing theme selection](https://user-images.githubusercontent.com/6124739/95618826-f864ca00-0a6d-11eb-9c53-5c31294c398e.jpg)

**Comment by arbor95** [comment]
![menu and header conflict](https://user-images.githubusercontent.com/6124739/95619620-30204180-0a6f-11eb-97b6-6672d3fbe74a.jpg)

not quite the same problem

**Comment by jon48** [comment]
Hello,

Please see my answer [on the forum](https://www.webtrees.net/index.php/en/forum/4-customising/34562-rural-theme-2-0-4-webtrees-2-0-4-up-to-2-0-6#81058).

You other points are consequences of that decision to stick the standard header structure defined by webtrees, and constraints on small screens:

- Keeping all the menus was not working nicely on small screens, so on those I am hiding a menu that I feel is less used than the other ones: the theme menu.

- The other issue will be difficult to fix for me: the menus have a transparent background, and their font is chosen to contrast against the deep brown of the background. It cannot detect that your image has a quite pale background, and that the font color will not contrast  enough. I would suggest you choose a darker background for your image to match the white font.

**Comment by jon48** [comment]
Hello

> It cannot detect that your image has a quite pale background, and that the font color will not contrast enough.

I stand corrected on that statement. After a bit of research, it appears that there is a CSS attribute `mix-blend-mode` that has some capabilities in that area.

I have done a bit of testing, and whereas it seems to do the job, I can see some random side effects on the font color, which I am not entirely satisfied with. Would you mind do some testing with the file attached (which is built on top of the 2.0.9-v.1 version just released)?

[rural.min.css.zip](https://github.com/jon48/webtrees-theme-rural/files/5433726/rural.min.css.zip) (to overwrite the file `modules_v4\myartjaub_ruraltheme\resources\css\rural.min.css`

**Comment by arbor95** [comment]
Hello Jonathan,
thx for 2.0.9-v.1 and the explanations.
I did a test with the "mix-blend-mode" - version and some headers and I think it does its work.
