### ISSUE TITLE
missing border

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#14]
![rural-border-missing](https://user-images.githubusercontent.com/6124739/96253862-a0b9e780-0fb4-11eb-91fa-1973c25991d7.jpg)

**Comment by jon48** [comment]
Hello

Would you be able to provide a bit more information on where or how you see this happening?
I cannot see it on your public website, and screenshots on issue #13 do not show it, so I guess it is happening only under specific circumstances.

As well, does it appear on all browsers, or only specific ones?

**Comment by arbor95** [comment]
Sorry,
That Problem has gone after installing the Developement version of the "fancy image Gallery".

**Comment by arbor95** [comment]
Gone

**Comment by arbor95** [comment]
I just disabled the "Fancy Imagebar" and now it is there again.

**Comment by arbor95** [comment]
Please tell me, if you have seen the bad behaviour, cause I will enable this again.

**Comment by arbor95** [comment]
I took a closer look at that:
the fancy imagebar inserts a padding for the rural :
[dir=ltr] .wt-theme-_myartjaub_ruraltheme_ .container-lg {
    padding-left: 15px !important;
    padding-right: 15px !important;
}
the normal padding for .container-lg (without the fancy imagebar) is done by:
[dir=ltr] .container-fluid, [dir=ltr] .container-lg, [dir=ltr] .container-md, [dir=ltr] .container-sm, [dir=ltr] .container-xl, [dir=rtl] .container-fluid, [dir=rtl] .container-lg, [dir=rtl] .container-md, [dir=rtl] .container-sm, [dir=rtl] .container-xl {
    padding-left: 5px;
    padding-right: 5px;
}

If change from 5px to 15px it looks ok.

**Comment by jon48** [comment]
Hello,
I assume that you were using webtrees 2.0.9. The theme was not updated yet for that version, and there was a slight change in the main layout that triggered this behaviour (this was not due to the fancy module).

The new version of the theme [2.0.9-v.1](https://github.com/jon48/webtrees-theme-rural/releases/tag/2.0.9-v.1) has just been released.
