### ISSUE TITLE
2.0.9-v.1 - Use agreement text not centered

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#15]
The use agreement text on the “Request a new user account” page (when **Control panel > Sign-in and registration > Show acceptable use agreement on “Request a new user account” page** is enabled) is not centered:

![image](https://user-images.githubusercontent.com/46184729/98340083-10981c80-200d-11eb-9b65-c70174f58b5b.png)

Is it possible to align it with the rest of this page?

**Comment by jon48** [comment]
I have aligned the text with the below box (the text itself is not centered, just aligned).
I slightly changed the small help texts as well, as I did not noticed they were not in line with the overall theme colors, and I prefer them aligned on the left.

This will be available with the next release.

![image](https://user-images.githubusercontent.com/5150782/98603692-69e8a000-22da-11eb-8b16-122183c39ce5.png)
