### ISSUE TITLE
Design of header

### ISSUE THREAD

**Issue by hartenthaler** [jon48/webtrees-theme-rural#2]
![Screenshot (106)_LI](https://user-images.githubusercontent.com/6324175/83696984-1755da00-a5fe-11ea-8cea-7f5371724b28.jpg)

I would prefer a shorter "search bar" so that more of the header image is visible. Is it possible to hide the tree title, maybe by a configuration option?

I like your design of Rural! Thank you for updating!

**Comment by jon48** [comment]
Hello,
It has been designed to be shorter indeed, as per the screenshot below (in Chrome).

Could you please confirm your browser (I guessed Edge from your screenshot), so that I can try to reproduce?

![Capture_Rural_#2](https://user-images.githubusercontent.com/5150782/83734640-32007100-a647-11ea-83ef-72bb11b19b2f.PNG)

**Comment by hartenthaler** [comment]
Oh! Always Microsoft! Yes, it was Edge. In Chrome it looks perfect. Just updated to the newest version of Edge (Version 83.0.478.44) - and now it is perfect in Edge, too! Thank you!

**Comment by jon48** [comment]
I was able to reproduce on my Edge (still in an older version), and indeed some CSS properties were not supported until version 79.
I have added a couple of fixes that should increase the compatibility with Edge. If affected, you can replace the file `/modules_v4/myartjaub_ruraltheme/resources/css/rural.min.css` with the file  in [this archive](https://github.com/jon48/webtrees-theme-rural/files/4731967/rural.min.css.zip)

I reckon I had done little browser compatibility testing, most of it being on Chrome. I discovered that the display in Internet Explorer 11 is pretty bad, but have little appetite to improve...
