### ISSUE TITLE
2.0.12-v.2 - black frame line at left side is missing after editing

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#25]
After editing a record a black frame line at the left side is missing.

![edit](https://user-images.githubusercontent.com/46184729/118351281-58b76f00-b55b-11eb-9304-6f3f9407a8e4.png)

Can this be fixed?

**Comment by jon48** [comment]
Thanks for reporting it.

Could you please try the file in [this archive](https://github.com/jon48/webtrees-theme-rural/files/6487979/rural.min.css.zip) (overwriting the `/modules_v4/myartjaub_ruraltheme/resources/css/rural.min.css` file)?

**Comment by TheDutchJewel** [comment]
Thanks for the quick fix: it works fine!
