### ISSUE TITLE
2.0.4-v.1 - Welcome text on login page not centered

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#3]
The welcome text on the login page is not centered enough, which looks weird:
![afbeelding](https://user-images.githubusercontent.com/46184729/83902837-6f572280-a75d-11ea-9c99-4302978a6c2c.png)

Is it possible to move the text more to the middle, just like in the standard webtrees theme?
![afbeelding](https://user-images.githubusercontent.com/46184729/83903801-12f50280-a75f-11ea-8e9b-28ba1a8ebe1e.png)

_Tested configuration_
Device: desktop pc
OS: Windows10 x64 Home v1909
Browsers: Edge v83.0.478.44 and Firefox v77.0.1
webtrees: 2.0.5

**Comment by jon48** [comment]
I agree, that would be better to be centered (the other themes do not actually have to worry about it, as they are just using the whole width), The difficulty is that there is no specific CSS selector for that text, so I have to find a way to apply style without affecting other areas.

I may have a solution using `.wt-main-container > p`, but would like to run more extensive tests to confirm. If I am happy with it, I will deliver it with a 2.0.4-v.2 version that will incorporate a couple of other fixes (and potential other feedback in the next couple of days),
