### ISSUE TITLE
missing possibility to switch the person of the interactive tree

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#31]
missing presentation for <...... class="wt-icon-individual tv_link tv_treelink"></a>
![missing switch to person](https://user-images.githubusercontent.com/6124739/121786589-02bd0200-cbc1-11eb-8541-6d3bef84a91d.jpg)

**Comment by jon48** [comment]
Thanks for spotting it.
This has been corrected in version 2.0.12-v.3.
