### ISSUE TITLE
Vertical alignment of counter part in Extend family module

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#33]
In the [Extended family module](https://github.com/hartenthaler/hh_extended_family), the counter part before the name is aligned very high in the Rural theme compared to the default webtrees theme:

![afbeelding](https://user-images.githubusercontent.com/46184729/127611519-e482dd4c-65d5-43e5-97c3-334fb841ec34.png)

![afbeelding](https://user-images.githubusercontent.com/46184729/127611163-2679b228-7aef-45b2-9d9c-8082c8569ba4.png)

What is the best way to fix this: in the Rural theme or in the Extended family module?

**Comment by hartenthaler** [comment]
As far as I can see, this happens only in the compact design version of my module "extended family".
```
#hh_extended_family_content_compact .wt-chart-box-m,
#hh_extended_family_content_compact .wt-chart-box-f,
#hh_extended_family_content_compact .wt-chart-box-u {
    display: flex;
    align-items: center;
    clear: left;
    float: left;
    border-radius: 5px;
    margin: 2px 0;
    width: 99%;
}

#hh_extended_family_content .wt-chart-box-m,
#hh_extended_family_content .wt-chart-box-f,
#hh_extended_family_content .wt-chart-box-u {
    clear: left;
    float: left;
    border-radius: 5px;
    margin: 2px 0;
    width: 99%;
```

The difference are the two new inserted lines:
```
    display: flex;
    align-items: center;
```

**Comment by jon48** [comment]
As Hermann suggest, the "misalignment" is not actually specific to the Rural theme, and can be seen on other themes as well (the difference of font size may make it slightly less obvious on the others):

![image](https://user-images.githubusercontent.com/5150782/127645836-0735ae01-c6cf-4515-b581-8ed086b984e7.png)

They are not actually not misaligned, the different text elements are just vertically aligned around their center line, and as the counter element is smaller (75% font size) than the name, its baseline is slightly above the one of the main text.
If you prefer to have the text aligned , then the CSS would need to replace `center` by `baseline` for the `align-items` property:

```css
align-items: baseline
``` 
![image](https://user-images.githubusercontent.com/5150782/127646956-82d84f9e-7ba0-4a5a-a0d4-6a372dd36bd6.png)

**Comment by TheDutchJewel** [comment]
>If you prefer to have the text aligned , then the CSS would need to replace `center `by `baseline `for the `align-items` property

That looks much better. I hope Hermann will fix this.

**Comment by hartenthaler** [comment]
Yes, this looks better. Is already fixed and tested, will be part of the next release! Thank you!
