### ISSUE TITLE
2.0.4-v.1 - Onglet Histoires 

### ISSUE THREAD

**Issue by zileg31** [jon48/webtrees-theme-rural#4]
Bonjour,
Le thème "Rural" v2.0 fait disparaître l'onglet "Histoires" sur les fiches individuelles. Dés qu'une histoire est écrite pour l’individu concerné.
Cordialement,
Jacques
![histoires-1](https://user-images.githubusercontent.com/66511505/83940085-3f9e2e00-a7e2-11ea-87dc-b4df00a1a849.png)

Tested configuration
Device: desktop pc
OS: Windows10 x64
Browsers: Firefox v76.0.1 (64bits)
webtrees: 2.0.5

**Comment by jon48** [comment]
Bonjour,
Merci de remonter ce problème. Je viens de le corriger, et il sera disponible dans la version 2.0.4-v.2 qui devrait être disponible à la fin du week-end.
