### ISSUE TITLE
Module causing an error in Webtrees 2.1.0

### ISSUE THREAD

**Issue by geugeu1** [jon48/webtrees-theme-rural#40]
The module is throwing an error when upgrading site to 2.1.0 of webtrees.

**Comment by jon48** [comment]
I have not published a version compatible with 2.1 yet. As Greg has mentioned a couple of times on the forum, for major updates, like 2.0 to 2.1, it is better to wait for the custom modules authors to confirm whether a new version will be required before updating webtrees.

Much of the work is already done and a final release should not take long now, but I still need to merge the latest changes from webtrees.

**Comment by geugeu1** [comment]
Thanks you

Le lun. 25 avr. 2022 à 20:55, Jonathan Jaubart ***@***.***> a
écrit :

**Comment by jon48** [comment]
Versions 2.1.0-v.1 & 2.1.1-v.1 of the theme have now been published.
