### ISSUE TITLE
GVExport preferences partially behind the webtrees menu

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#42]
When using the **GVExport module** by @[tillsc](https://github.com/tillsc/GVExport) (for webtrees 2.0.x) or by @[Neriderc](https://github.com/Neriderc/GVExport) (for webtrees 2.1.x) and Rural, it is not possible to close the Diagram preferences because the close button is behind the webtrees menu.

Here is a screenshot with the default webtrees theme:
![afbeelding](https://user-images.githubusercontent.com/46184729/168413407-7b5c64df-62da-4820-b0a3-ad010267b788.png)

And here a screenshot with the Rural theme:
![afbeelding](https://user-images.githubusercontent.com/46184729/168413312-b25c30d3-49b9-4737-98b4-e5983996c4c2.png)

**Comment by jon48** [comment]
Which browser are you using?

I have tried reproducing on Chrome 101, Firefox 100 and Edge 101, with the following configurations, and in all cases, the preferences window displayed above the menu.

- webtrees 2.0.23 - Rural theme 2.0.23-v.1 -  tillsc/GVExport@master
- webtrees 2.1.2 - Rural theme 2.1.1-v.1 - Neriderc/GVExport@master

![image](https://user-images.githubusercontent.com/5150782/168420501-f026d649-5aaa-4171-8f24-a93f7030685f.png)

**Comment by TheDutchJewel** [comment]
I tried it with Edge 101, Firefox 100 and Opera 86: they all have the same problem.

**Comment by TheDutchJewel** [comment]
Aha, the problem is caused by the [Vesta Classic Look & Feel module](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf): if I disable that one then the problem is solved.

**Comment by vytux-com** [comment]
So you are trying to use two theme modules at the same time... Of cause this is not going to work well

**Comment by TheDutchJewel** [comment]
@vytux-com 
>So you are trying to use two theme modules at the same time...

Why do you think that?

I only use the Rural theme and in case of problems I show how it looks with the default webtrees theme.

**Comment by vytux-com** [comment]
> @vytux-com
> 
> > So you are trying to use two theme modules at the same time...
> 
> Why do you think that?
> 
> I only use the Rural theme and in case of problems I show how it looks with the default webtrees theme.

The classic laf is basically a theme module it's supposed to convert webtrees modern theme into webtrees classic (V1) theme.

Using it on any other theme is just asking for trouble

**Comment by jon48** [comment]
> The classic laf is basically a theme module it's supposed to convert webtrees modern theme into webtrees classic (V1) theme.
> 
> Using it on any other theme is just asking for trouble

I have raised that concern on the issue raised by @TheDutchJewel on the Classic Look & Feel repository.
Even though it is not advertised as is, it is indeed closed to a theme module, and I feel it should only apply when a standard theme is selected, not for the other custom themes, as CSS conflicts are quite likely (or in a more controlled manner).

**Comment by ric2016** [comment]
@jon48 
Can you give an example of a conflicting css definition from the Classic Look & Feel module? I don't notice any obvious issues when using both modules together (except from this one, which is actually about a third custom module).

> Using it on any other theme is just asking for trouble

No, it is supposed to work together with themes in general. Note also that it has several non-theming-related aspects.

**Comment by hartenthaler** [comment]
Using the latest version of the Vesta modules this error is solved now. So from my point of view, this issue can be closed now.
