### ISSUE TITLE
2.1.3-v.1 - family page: boxes for missing partner are missing

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#43]
Based on this topic ([family page css seems somewhat scrumbled](https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37004-family-page-css-seems-somewhat-scrumbled)) on the webtrees forum  I checked this with the rural theme on webtrees 2.1.5.

The problem is fixed in the webtrees default themes, but it still exists in the rural theme: on the family page the boxes for the missing partner are missing:

![afbeelding](https://user-images.githubusercontent.com/46184729/172023285-47270e39-3ec6-4f4f-92d7-9ab3d5080e44.png)

**Comment by jon48** [comment]
The release compatible with webtrees 2.1.5 is now available.
