### ISSUE TITLE
adjust size of person box to see all content

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#44]
You can configure the content of a persons info-box, but the content is truncated. 
Perhaps the size of the info-box can be resized dynamically corresponding to real content. 
In webtrees theme it seems to be a fixed hight depending on the content.
see:
![rural-theme](https://user-images.githubusercontent.com/6124739/173192458-07017e52-417c-433d-98d0-00254eb707d4.jpg)
![webtrees-theme](https://user-images.githubusercontent.com/6124739/173192461-0cc73b13-9325-4aa0-b7dd-b226c6d5194a.jpg)

**Comment by jon48** [comment]
Hello,
This is not really an issue with the Rural theme itself, as you can see with boxes on my own website, which are larger than yours.

![image](https://user-images.githubusercontent.com/5150782/173249532-e45a59e7-4419-46cc-b62a-3af9e3499082.png)

The theme does not set the height of the boxes (hence allow for dynamic sizing), but looking at your website, you have enabled the CustomCSS module, which add some additional CSS, and for instance a fixed width and height for the chartboxes. As the `rem` base is not the same between the standard themes and the rural one, the boxes look smaller.
In my opinion, as custom CSS is aimed at the standard themes, it should not be enabled at the same time as the Rural theme, as it is not taking into account its specificities.

**Comment by arbor95** [comment]
Thx for your information.
For me as newbie of webtrees the dependencies of checking options or enabling modules are not always obvious or clear.
Sorry for taking your time.

**Comment by makitso** [comment]
As noted in the description of custom-css it works with standard themes only.  So, you have two options;
1.  remove the custom-css module or
2. delete lines 87-92 of custom-css/resources/css/custom.css
