### ISSUE TITLE
Place hierarchy (part of Vesta extentions by ric2016) not displayed correctly with Rural Theme

### ISSUE THREAD

**Issue by CHTHSCH** [jon48/webtrees-theme-rural#45]
![image](https://user-images.githubusercontent.com/50621196/174002395-f43569ae-91df-4a48-b024-9fa3bfc049df.png)

Environment:
webtrees 2.1.5
rural theme 2.1.5.-v.1
vestas extensions 2.1.5.0.0.

Issue: the map in the place hierarchy provided by the vestas extensions of webtrees is not displayed correctly using the rural theme. See picture

**Comment by jon48** [comment]
Hello,
Are you sure that you have correctly installed version 2.1.5-v.1 of the theme?
From what I can see and from the content of [the CSS file on your site](https://webtrees.schmidt-himmelskamp.de/index.php?route=%2Fmodule%2F_myartjaub_ruraltheme_%2FAsset&asset=css%2Frural.min.css&hash=1597900497), it looks more like a version 2.0.xx installed on a webtrees 2.1.5. There are a few majors other problem with the display which are typical of that case (the misalignment of the header, the blue font in the menu...)

![image](https://user-images.githubusercontent.com/5150782/174163233-ddfa919c-fa20-4229-bafd-792bc4ba822c.png)

I have tried to install the Vesta module on my PC, and I cannot notice any issue with the map

![image](https://user-images.githubusercontent.com/5150782/174163634-6ea5459c-c95b-4ef5-bd72-c4c8fee6ce75.png)

**Comment by CHTHSCH** [comment]
Removed the vestas modules and rural theme and re-installed. All working now.

Thanks for support.

**Comment by CHTHSCH** [comment]
Your hint helped. All working now
