### ISSUE TITLE
Body part display boundary

### ISSUE THREAD

**Issue by iyoua** [jon48/webtrees-theme-rural#47]
First of all, thank the theme author for his contribution! When browsing web pages on mobile devices, you will find that there is more white space on the left and right sides of the main body, which reduces the display area of the text content, and the proportion is not harmonious, affecting the appearance. It is suggested to expand the area marked by the red line to the green line. Best wishes!
![white](https://user-images.githubusercontent.com/102014216/179513832-7d8c9b08-0872-4818-9d70-01c2509bb54a.jpg)

**Comment by jon48** [comment]
Hello,
Indeed, I had a few struggles with the outermost spacing of the frame.
I am not going to have a lot of time in the next few weeks to look into it, and limited access to my development tools, but I am keeping the issue open for a quieter period.
