### ISSUE TITLE
2.0.4-v.1 - More space for logo on login page

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#5]
On the login page, the logo (150px height) disappears behind the text:
![afbeelding](https://user-images.githubusercontent.com/46184729/83942489-17b7c600-a7f4-11ea-9435-065d80a7c544.png)

Is it possible to move the text section down to make room for the logo?

**Comment by jon48** [comment]
Hello,
You are actually missing a large part of the header (the Search form, and even the main menu), as you can see in the screenshot below,
I am struggling to reproduce this issue on the browsers I use. 

Could you please precise what browser you are using, and if you have tried on other ones? Are you using the standard logo, or a personal one? Do you see this issue on all pages, or only the login page?

![Capture_Rural_#2](https://user-images.githubusercontent.com/5150782/83734640-32007100-a647-11ea-83ef-72bb11b19b2f.PNG)

**Comment by TheDutchJewel** [comment]
_Tested configurations_
1. Desktop pc with Windows10 x64 Home v1909 and latest versions of Edge (83.0.478.44), Firefox (77.0.1), Waterfox (2020.06), Chrome (83.0.4103.97), Vivaldi (3.0.1874.38).
2. Tablet with Android 8.1.0.
Tested with online (private) and offline page (XAMPP v7.3.18-0).

Same problem in all browsers, **only on login page**, with and without logo. I just created a demo one for the schreenshot.

**Comment by TheDutchJewel** [comment]
Here is a screenshot of the login page with the default logo:
![afbeelding](https://user-images.githubusercontent.com/46184729/83945951-2a3ef900-a80e-11ea-916e-ca17b6c48a24.png)

>I am struggling to reproduce this issue on the browsers I use.

You should see it when you log out.

**Comment by jon48** [comment]
OK, I see it now, this is happening when none of your trees are available to visitors (in my case, I always have at least one). 
In that case, neither the search box, nor the tree title are displayed, and I am missing two third of my header, and the height is too small.

I am going to think about that use case, as I can now reproduce.

**Comment by jon48** [comment]
And the fix was pretty obvious actually.

The only issue I still see with that use case is that I cannot have the white section with the round corners, as is usually the case when a menu is displayed, because the CSS logic for it is in the navigation pane, and the main section does not have a way to know that the navigation pane is not displayed (except maybe through some JavaScript, but that may be overkilled),

Happy with the rather empty right side?

![image](https://user-images.githubusercontent.com/5150782/83949428-9d02a100-a81b-11ea-820b-8b4bedc668fe.png)

**Comment by TheDutchJewel** [comment]
>Happy with the rather empty right side?

No problem with that. Thanks for fixing!

**Comment by jon48** [comment]
I will go with it then.
I am waiting just a bit in case of further general feedback, but will probably release a new version with the latest fixes tomorrow.
