### ISSUE TITLE
new Version Info

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#51]
Can you please inform (at least in control panel), if an updated version is available? (It has not to be that strict as vesta does.)

**Comment by jon48** [comment]
This feature already exists since version 2.0.23-v.1.
It is using the native module version checker, and it should display a message in the Control Panel when a new version is available (there may be a 24h delay due to webtrees caching).

![image](https://user-images.githubusercontent.com/5150782/188955292-be414e98-e95b-477d-b4a4-368a97cad26b.png)

It is calling an endpoint I am hosting, and the latest version is calculated based on the installed version of webtrees, so if you are still on webtrees 2.1.6, it will not suggest 2.1.7-v.1.

**Comment by arbor95** [comment]
I am on wt 2.1.7 and  rural was on 2.1.5.1.
I did not get the message until this morning

**Comment by jon48** [comment]
That would fall within the expected timeframe then.
The rural 2.1.7-v.1 version is still very new, and was publicized for upgrade on the version checker only yesterday morning, so with the potential 24-hour caching lag, it is possible the message appeared only this morning.

**Comment by arbor95** [comment]
I will give it a try next update

**Comment by jon48** [comment]
I have just released version 2.1.8-v.1, around 12pm GMT today.
Assuming that you update to version 2.1.12 of webtrees (or at least 2.1.8), you should hopefully see the notification in your control panel at some point in the next 24 hours. Let me know if if still has not appeared on Monday.

**Comment by arbor95** [comment]
still no release info
![controlPanel](https://user-images.githubusercontent.com/6124739/213993870-5fbe4203-f716-46ec-94a2-06ecfab95ac0.jpg)
![installedVersion](https://user-images.githubusercontent.com/6124739/213993874-01975602-30ce-4662-b27e-391a246f6b61.jpg)

**Comment by jon48** [comment]
2.1.16-v1 was published yesterday around 7pm GMT, so at the time of your message, you were still within the 24 hours that it can take for the core version checker before contacting the update URL.

The new version should appear a some point from now or in the morning.

**Comment by arbor95** [comment]
I still haven't received a notification.
January 24, 2023 9:10 am

![noNewVersion](https://user-images.githubusercontent.com/6124739/214241642-755e8740-4df5-46fe-8b85-d937a4d9aded.jpg)

**Comment by jon48** [comment]
Now that is more surprising, as the version check should have kicked in.
So, either the check is not triggered for a reason I cannot explain, or it is triggered but your installation has trouble connecting to my Update URL.

Unfortunately, the logic managing the version check is part of the webtrees core code, not part of the module, so there is nothing I can force here.
To troubleshoot, I suggest you replace the file `app/Module/ModuleCustomTrait.php` by [the attached](https://github.com/jon48/webtrees-theme-rural/files/10497769/ModuleCustomTrait.zip) (keep a copy of the previous file, you can restore it after the tests). It simply adds some logging to that part of the process.

After 24 hours, check in your website logs ("Webseitenprotokolle" I guess from your screenshot below), filter by type "config", and 
check if you have some entries related to \_myartjaub\_ruraltheme\_ . You should at least have an entry "Contacting url for \_myartjaub\_ruraltheme\_: ...", that will be the proof that the check is triggered, then depending on what other message follows, there might be a clue.

![image](https://user-images.githubusercontent.com/5150782/214524378-3b2b54af-9b4e-4c98-b50d-43c659db0040.png)

**Comment by arbor95** [comment]
Error version _myartjaub_ruraltheme_: Client error: `GET https://apps.jaubart.com/myartjaub/webtrees-modules/api/module/myartjaub_ruraltheme/latest?m=2.1.16-v.1&w=2.1.16&p=8.1.14&o=u&s=87aa5333-2cc7-4e78-a42c-5d23c660a86b` resulted in a `415 Unsupported Media Type` response:

**Comment by jon48** [comment]
Thanks. It is fair to say I was ready to see an error, but not this one... 

Interestingly, based on your siteID, and looking through the HTTP log, I cannot see any request from it since July (there were a few before that), so I am wondering if something interferes with it before it reaches my endpoint (maybe on my webhost's side).

As I am still a bit lost for an explanation, can I ask you to test another `app/Module/ModuleCustomTrait.php` ( 
[attached](https://github.com/jon48/webtrees-theme-rural/files/10517983/ModuleCustomTrait.zip))? It is trying to capture more information about the request and response from the update API.

![image](https://user-images.githubusercontent.com/5150782/215066605-661c91e0-07d2-4a80-b945-3908568350ec.png)

By the way, do you have other custom modules (besides the Vesta ones, which overwrite the core latest version mechanism), and if so, do you receive updated notification from them?

**Comment by arbor95** [comment]
here the log from today:
https://apps.jaubart.com/myartjaub/webtrees-modules/api/module/myartjaub_ruraltheme/latest?m=2.1.16-v.1&w=2.1.16&p=8.2.1&o=u&s=87aa5333-2cc7-4e78-a42c-5d23c660a86b
gives:
No error but not HTTP 200, or not a valid version.

fyi: 
1. Other modules retrieve a txt-file for getting the version - number! (hh_extended_family, GVExport seem to work)
2. I activated php 8.2

**Comment by jon48** [comment]
OK, that is even more confusing, as this uses a different branch of the code than the one in your first log... Meaning, it apparently managed to connect, but could not retrieve any meaningful content.

Can you try with [the attached](https://github.com/jon48/webtrees-theme-rural/files/10528081/ModuleCustomTrait.zip), which add logs to that other branch?...

> 1. Other modules retrieve a txt-file for getting the version - number! (hh_extended_family, GVExport seem to work)

Technically, if everything is working, from your website's perspective, my update URL also serves a text file. I just wanted to check if those other modules were using the webtrees native version checker (the 2 you mention do), or their own (like Vesta). So this is pointing more with a specific error with retrieving data from my website.

**Comment by arbor95** [comment]
[webtrees-logs.csv](https://github.com/jon48/webtrees-theme-rural/files/10528324/webtrees-logs.csv)

I got the new attached now at 22:30. Here the config-entries with the other modules. (So till tomorrow, with the new attached)

**Comment by arbor95** [comment]
[webtrees-logs.csv](https://github.com/jon48/webtrees-theme-rural/files/10530897/webtrees-logs.csv)
hopefully helpul.

**Comment by jon48** [comment]
Thanks. Very helpful indeed, and that confirms that something is “interfering” with the request, which never reaches the webserver itself.

It appears from the response data that a security shield (Imunify360) is analysing the request to identify potential threats, and offer a challenge for those suspicious (a bit like Captchas). It seems that it identifies your request as suspect, and the webtres version checker is not able to handle the challenge (understandably).
To be honest, I was not even aware that my web host had that feature, so I will contact them to try and understand a bit more how this is working, if it is possible to understand why it does not allow your website but some others are, and if there is a way to allow this traffic through (it may not be possible at all, given the nature of the shield).

In order for me to get some info for them, is the issue with your public website https://freris.de (IP 81.169.145.64), or a private installation?

You can restore the original file from webtrees if you want, I think I have the information I needed now.

**Comment by arbor95** [comment]
The system is handled by strato.de .
I have no root access.
I can create the db and upload data.
I can not install any additional apps.
Only those prooved by strato.

**Comment by arbor95** [comment]
seems as if there is still no info "update available". I just copied your module for 2.1.16 to https://dfrese.de . So I think I should get an info about 2.1.17 of rural is available.

**Comment by arbor95** [comment]
still no info for version availability of version 2.1.18... .
I did not update yet.
Can I test something, to find the bug?

**Comment by arbor95** [comment]
I just have been looking: There is an info. Thx!!!
