### ISSUE TITLE
Change in the way to edit the name of a record in the new version of RURAL

### ISSUE THREAD

**Issue by BernatBanyuls** [jon48/webtrees-theme-rural#52]
In the new version, the [v] symbol under the name to check your registration has disappeared. You now go directly to the editing screen (by clicking on the pencil). This is not bad, but I need the previous step because some of my records have "common notes" that I can't read now. It appears for a few seconds on the screen, but the system quickly goes to edit and does not allow reading. In other presentations it does NOT happen, only in RURAL and it is my preferred presentation mode. See if you can help me.

(I hope I made myself clear)
Thank you.

**Comment by jon48** [comment]
Sorry, I do not visualise what "[v] symbol under the name to check your registration" you are referring to. Would you mind sending a screenshot or the path to the page?

At a first glance, I am a bit surprised any behaviour is changed by the theme, as it is only a CSS theme (no HTML override nor additional JavaScript), so only display should be impacted. But when I have located the area you are describing, maybe I will be able to find something.

**Comment by BernatBanyuls** [comment]
Let's see. I understand that it is a bit difficult to explain and the only way to recover the image would be with a previous version.
In the screenshot I point out in a red circle where before there was an icon that allowed you to see the registry data. If you then had to change something, you clicked on the pencil icon.
In screenshot 1 is what I see in the current edition and in screenshot 2 the icon that appeared before in the area marked in screenshot 1.
![image](https://user-images.githubusercontent.com/103060233/191217908-04a39421-d6b3-470d-94ec-598af151f7e8.png)

![image](https://user-images.githubusercontent.com/103060233/191218053-e498d77d-ec95-4afe-8355-4589751a37d2.png)

In the other presentations everything is fine, but in Rural there is a jump of one or two seconds that goes from "show name record" to "name edition". (I hope this doesn't just happen to me, I wouldn't understand why).

**Comment by jon48** [comment]
I am still not sure I understand which icon was displayed (and disappeared), as there should be nothing under the name.
From your screenshot, I however believe that you have some other modules installed (at least Vesta), as some of the displays are not the standard ones (the page title/name does not have the same information, the icons for editing are not visible in the standard theme, there is a Sex bar below the Name, the Facts tabs is the Vesta one).

![image](https://user-images.githubusercontent.com/5150782/191339349-0d754121-906a-4398-8d7e-9aedffdd57df.png)

In the native webtrees, the edit buttons should appear when you open the name information.

![image](https://user-images.githubusercontent.com/5150782/191338627-5d3827c8-4c39-4648-919a-e03478c5e38c.png)

Could you please provide a screenshot when switching to another theme for which the icon appear?
As well, could you please temporarily disable the custom modules, and check that the name accordion behave as expected?

**Comment by BernatBanyuls** [comment]
We continue...
I have been going through all the "submissions" and they have all removed the icon I claim. Only the "MINIM" presentation (attached images) keeps it.  When I click on this icon, the registration information appears in an "accordion". For me it is important the information I add in the "note" and which refers to a small study of the surname.
Currently, in the rest of the "presentations" this "accordion" icon has disappeared and I can only click on the pencil icon. When I do so, the action that appears is the example in image #2, but it "doesn't stop". That is, in a second it disappears and goes straight to the edit screen. 
I think you can try to add a text in the "common note" of an individual and you will see how it is impossible to read it when you visit this page.
![errornote1](https://user-images.githubusercontent.com/103060233/191442729-065566ca-6359-40a2-a76c-96d6344a834c.jpg)
![errornote1_rural](https://user-images.githubusercontent.com/103060233/191442770-59b4c872-7a94-4fbf-b187-1f335f0cfe20.jpg)


![errornote2](https://user-images.githubusercontent.com/103060233/191441353-1c3d0fbd-2f96-49f2-89bb-4ffc3a186563.jpg)
b-1963-45d7-ba5e-a5606e13c740.jpg)
92-48a8-bb1d-e11d13602567.jpg)

![errornote2_rural](https://user-images.githubusercontent.com/103060233/191441365-fa888d98-3ef6-46de-911d-b8c290addad4.jpg)


![errornote3](https://user-images.githubusercontent.com/103060233/191441629-4d4de1bb-f1c4-4add-bf91-56c36415140f.jpg)
![errornote3_rural](https://user-images.githubusercontent.com/103060233/191441384-5def0330-8b98-4b54-8eaa-16e30ae25a1c.jpg)


![errornote4](https://user-images.githubusercontent.com/103060233/191441399-12b537af-5eae-4cff-ab82-750db68043ab.jpg)
![errornote4_rural](https://user-images.githubusercontent.com/103060233/191441415-0b1c6155-f7de-4db9-87ed-cfff7590e73d.jpg)

**Comment by jon48** [comment]
OK, thanks. I think this is clearer to me.
I do not think that the [v] should appear in any theme except Minimal. The [v] is actually the Bootstrap default, but this is replaced by the little triangle on the left in most themes. 

![image](https://user-images.githubusercontent.com/5150782/191467722-db3d3045-2528-4751-91d1-e9f2a805c821.png)

If a [v] was appearing before, it is more likely that a custom module was interfering with the theme, and preventing the expected CSS to be applied. Even on the Rural theme, as far back as webtrees 1.7, this was a triangle that was appearing.

[EDIT: actually, I found one [screenshot](https://www.webtrees.net/index.php/en/forum/attachment/7739) of your site in the webtrees forum. I looks like you were using a version of the theme not compatible with the version of webtrees, like theme 2.1.x on webtrees 2.0.x or vice-versa. The design is not the one expected]

![image](https://user-images.githubusercontent.com/5150782/191467413-d7873878-c3f1-40c9-80dd-9dc656060c94.png)

You should not click on the icons on the right to open the accordion, but anywhere else on the bar (again, those icons are not there in the standard webtrees, you probably are using some custom modules that are changing the display). If you click on the icons, that will redirect you to the appropriate edit page instead.

![wt_ISS52](https://user-images.githubusercontent.com/5150782/191468654-d9dcaa53-e88a-413e-b93c-ac13eceed2d4.gif)

If this is not what you are observing, please temporarily disable custom modules (the ones you copied in the /modules_v4/ folder), and that should work as expected.

**Comment by BernatBanyuls** [comment]
Perfect!!!!

Please excuse me.

Indeed, that's what I was looking for, but as I always did it using the icon (v) and now I didn't have it, I thought you had modified it.

Again, thanks for your help and a thousand apologies for my clumsiness.

Everything works perfectly and I take this opportunity to congratulate you for your "rural" for me is the best by far. Thank you.

**Comment by jon48** [comment]
Great, glad we could get to the bottom of it.

Enjoy webtrees!
