### ISSUE TITLE
No aparece la "opción CENSO" en Catalán

### ISSUE THREAD

**Issue by BernatBanyuls** [jon48/webtrees-theme-rural#53]
Greetings.

I have just checked that the CENSUS (events) option does not appear in CATALAN (it appears perfectly in SPANISH).  I use webtrees in Catalan and I couldn't find the CENSUS event although I have activated the module.
The translation would be CENS 
Thank you.

**Comment by jon48** [comment]
Hello,

As I mentioned in issue #52, the rural theme only changes the layout and colours, but does not really interfere with the application logic, so there is no reason for some options to be missing because of the theme (the only exception being if those options are accessed through icons). 

I can see the "Empadronament" event in the list of events on my installation, which is the current Catalan translation for Census. 

![image](https://user-images.githubusercontent.com/5150782/195298717-08292f33-6c9b-4d01-b781-2985be7dc188.png)

If this translation is not correct, you can change it on https://translate.webtrees.net/ (which is currently having some certificate issues), or ask Greg to amend it.

**Comment by BernatBanyuls** [comment]
Thank you Jonathan for your explanations.

Indeed, I knew that RURAL was a layer, but that's why I didn't understand how I couldn't find the CENSUS option. 

Although it doesn't mean exactly the same thing, the "empadronamient" option may work for me (it may even be the correct one) and as I had never used this "fact" I didn't know how it works or where to find it (well, in Spanish it does).

Now I am going to study how I can incorporate my censuses to be able to use them in webtrees. I don't see it very clear, so I will have to study it. If you know of any place where I can get more information, I would be grateful if you could let me know.

Anyway, thanks for your help. 

 

 

 

 

 

 

Abans d'imprimir aquest correu, penseu si és necessari.

Aquest correu electrònic pot contenir informació confidencial o legalment protegida i està exclusivament adreçat a la persona o entitat destinatària. Si no sou el destinatari final o la persona encarregada de recollir-lo, no esteu autoritzat a llegir-lo, retenir-lo, modificar-lo, distribuir-lo, copiar-lo ni a revelar-ne el contingut. Si heu rebut aquest correu electrònic per error, us preguem que informeu el remitent i elimineu del vostre sistema el missatge i el material annex que pugui contenir. 
Gràcies per la vostra col·laboració.

 

De: Jonathan Jaubart ***@***.***> 
Enviat: dimecres, 12 d’octubre de 2022 11:03
Per a: jon48/webtrees-theme-rural ***@***.***>
A/c: BernatBanyuls ***@***.***>; Author ***@***.***>
Tema: Re: [jon48/webtrees-theme-rural] No aparece la "opción CENSO" en Catalán (Issue #53)

 

Hello,

As I mentioned in issue #52 <https://github.com/jon48/webtrees-theme-rural/issues/52> , the rural theme only changes the layout and colours, but does not really interfere with the application logic, so there is no reason for some options to be missing because of the theme (the only exception being if those options are accessed through icons).

I can see the "Empadronament" event in the list of events on my installation, which is the current Catalan translation for Census.

 <https://user-images.githubusercontent.com/5150782/195298717-08292f33-6c9b-4d01-b781-2985be7dc188.png> 

If this translation is not correct, you can change it on https://translate.webtrees.net/ (which is currently having some certificate issues), or ask Greg to amend it.

**Comment by jon48** [comment]
> Although it doesn't mean exactly the same thing, the "empadronamient" option may work for me (it may even be the correct one)

If a better translation is available in Catalan, feel free to suggest it on the webtrees forum.

> Now I am going to study how I can incorporate my censuses to be able to use them in webtrees. I don't see it very clear, so I will have to study it. If you know of any place where I can get more information, I would be grateful if you could let me know. Anyway, thanks for your help.

I am not very familiar with the census feature in webtrees, as I have rarely used them in my genealogy.
One of the difficulty you are probably going to face is that I do not believe the census templates have been defined for Spain, so the census assistant will probably be of limited or no use.
