### ISSUE TITLE
2.1.7-v.1 - Left over characters after Charts > Timeline > Remove individual

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#56]
After removing an individual on the timeline (Charts > Timeline > Remove individual):

![afbeelding](https://user-images.githubusercontent.com/46184729/203850261-77ded4c2-aee7-40ca-86ce-b41b547a9a55.png)

some characters remain in the lower left corner:
![afbeelding](https://user-images.githubusercontent.com/46184729/203850581-4ff9ff7c-7fb7-4777-9639-56452f9ffe3e.png)

Tested with Rural 2.1.7-v.1 on webtrees 2.1.7

**Comment by jon48** [comment]
Thanks for the report, I confirm I can reproduce that behaviour as well on my theme only.

I have not managed to figure out what is causing the issue though yet, and what makes my theme behave differently from the others for that area, especially considering that the styling is mostly hardcoded inline by webtrees there.
I will need a bit more time on that one...

**Comment by jon48** [comment]
I still have not managed to understand the fundamental cause of why my theme is behaving differently from the other on that topic.
I have however implemented a hacky way of dealing with it, so hopefully that will work for you as well.
The "fix" is available in version 2.1.8-v.1.
