### ISSUE TITLE
Places right side missing on small devices

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#59]
See (is it possible to show/use):
![Screenshot_20230309-230317_Chrome](https://user-images.githubusercontent.com/6124739/224172638-8c57cef6-2a14-470a-bca5-edd628faf907.jpg)

![Screenshot_20230309-230414_Chrome](https://user-images.githubusercontent.com/6124739/224172693-1f91b98a-1957-4af9-991d-e0140fe32378.jpg)
Mi

**Comment by jon48** [comment]
Hello,
I am not sure I understand: on smaller resolutions, as there is not enough space on the right, the places list is below the map, so you just need to scroll down to see them. (Actually, this is something I am inheriting from the core webtrees, I do not do anything specific for that in the theme)

**Comment by arbor95** [comment]
I think it was not below. After this issue I changed some css for the footer to always show at bottom.

**Comment by arbor95** [comment]
will be solved, when https://github.com/jon48/webtrees-theme-rural/issues/62 is solved

**Comment by jon48** [comment]
I prefer to keep the issue open until I have a chance to test it with the 2.1.17 update.

**Comment by jon48** [comment]
As I was not able to understand/reproduce this one initially, and you think that this will be solved with the 2.1.17 update, I am closing this issue. Reopen it if necessary.
