### ISSUE TITLE
Carte d’ascendance: bottom

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#60]
The bottom Text is not at bottom
![Screenshot_20230318-114240_Chrome](https://user-images.githubusercontent.com/6124739/226100906-739db3f6-fccd-4443-ace5-5e694379c4db.jpg)

**Comment by jon48** [comment]
This one I can reproduce, and this is one I am inheriting by applying the same recipe as the core themes (you can see the webtrees logo in  the middle of the place list on those themes).

I have the feeling that this is coming from setting the `height: 70vh` at the whole map wrapper element, but if I set it a bit lower, then I have an issue at normal resolutions to align heights of the map and the list. I need to think more about that one.

![image](https://user-images.githubusercontent.com/5150782/229347716-0fb38e91-b3a7-468b-9199-37167d8f6935.png)

![image](https://user-images.githubusercontent.com/5150782/229347792-050e62ca-f109-409f-a5bd-dad49fa2293a.png)

**Comment by arbor95** [comment]
I add this css, seems to solve:

.wt-pedigree-map-map, .wt-pedigree-map-sidebar,
.wt-place-hierarchy-map, .wt-place-hierarchy-sidebar,
.wt-places-tab-map, .wt-places-tab-sidebar { height: 70vh; }
.wt-pedigree-map-wrapper, .wt-place-hierarchy-wrapper, .wt-places-tab-wrapper {	height: auto; }

**Comment by arbor95** [comment]
will be solved, when https://github.com/jon48/webtrees-theme-rural/issues/62 is solved

**Comment by jon48** [comment]
Solved in 2.1.17-v.1
