### ISSUE TITLE
Places in wt 2.1.17

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#62]
Since 2.1.17 on small devices:
Theme webtrees
![Screenshot_20230714-220648_Chrome](https://github.com/jon48/webtrees-theme-rural/assets/6124739/d916dcfd-3734-4fad-83f5-8813ca5dcbc9)
Theme rural:
![Screenshot_20230714-220412_Chrome](https://github.com/jon48/webtrees-theme-rural/assets/6124739/121d4ee6-6fa6-446e-9557-a3a9d73c085a)
Page is at https://freris.de/tree/frese/individual/XI36/Josef-Rumpf

**Comment by arbor95** [comment]
It seems as if the changes from https://github.com/fisharebest/webtrees/pull/4798 have to be implemented in your theme.

**Comment by arbor95** [comment]
Could you please fix this error please. I use the Places tab as the first tab and if there is no map it is really not nice. The error only shows up on mobile phones or on a correspondingly reduced window.

**Comment by jon48** [comment]
I am currently on holidays, and have not provided a version tested and compatible with 2.1.17 yet.
There are a few more commits to integrate than just 4798.

I will not be able to work on it until at least this weekend.

**Comment by arbor95** [comment]
you can see a working solution at
https://github.com/06Games/Webtrees-ArgonLight/commit/2ada337b201b3987ca024d1e3637bc269f2155ab

**Comment by jon48** [comment]
The version 2.1.17-v.1 of the Rural theme has just been released.
