### ISSUE TITLE
2.1.21-v.1 does not work with wt 2.2.x

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#66]
does not work with wt 2.2.x
app( 
is not replaced by 
Registry::container()->get(
and additional
use Fisharebest\Webtrees\Registry;
is not inserted

**Comment by jon48** [comment]
As per the release description, 2.1.21-v.1 is not supposed to work with 2.2, only with the 2.1 branch.

The release compatible with 2.2 will come later this week. I thought I would have had time to work on both yesterday, but some snags on the 2.1 version took me longer than expected.
There are a couple more changes I want to add to 2.2 beyond the replacement of the app global function .
