### ISSUE TITLE
2.0.4-v.1 icônes de localisation

### ISSUE THREAD

**Issue by zileg31** [jon48/webtrees-theme-rural#7]
Bonjour,
Je viens de constater que les trois icônes de localisation en Latitude et Longitude "Google" "Bing" et "OpenStreetMap" sont masquées par une icône de remplacement noire. Cet affichage n'est pas facile à interpréter. Pouvez-vous y remédier ?
Cordialement,
Jacques
![localisation](https://user-images.githubusercontent.com/66511505/83962780-7d618c00-a8a0-11ea-988a-6717fa1d96f6.png)
![localisation2](https://user-images.githubusercontent.com/66511505/83962808-c6194500-a8a0-11ea-9e4c-858ad5733f3b.png)

**Comment by jon48** [comment]
Bonjour,
C'est déjà corrigé dans le code (commit 083bf0b95be7a3a10a11aa620ffdcb2fffafe11a), et la nouvelle version devrait être livrée un peu plus tard aujourd'hui.

**Comment by zileg31** [comment]
Bonsoir Jonathan,
Merci pour pour ces correctifs ! L'onglet "Histoire" est revenu et les icônes de localisation sont claires. 
Il ne reste plus à nos amis développeurs de Webtrees de corriger l'absence de gestion des médias ! Et de remettre le choix de la photo principale comme portrait d'identité ... Une petite régression qu'a connu la version 2.0.
Cordialement,
Jacques
