### ISSUE TITLE
2.0.4-v.2 - Sources and notes are expanded by default

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#9]
When I use a default webtrees theme, all sources and notes on the 'Facts and Events' pages are collapsed, with the + sign. This is correct.

But when I change the theme to Rural, the + sign is still there but the sources and notes are all expanded. This is not correct.

_Tested configuration_
Device: desktop pc
OS: Windows10 x64 Home v1909
Browsers: Edge v83.0.478.44 and Firefox v77.0.1
webtrees: 2.0.5
PHP: 7.3.17-1

**Comment by jon48** [comment]
Hello,
Indeed, I wished I saw that before releasing v2  😅 

I have just fixed it for the sources, but could you confirm if you actually have the issue with notes? They seem to behave correctly on my side, or maybe I am not looking at the correct use case.

**Comment by TheDutchJewel** [comment]
> could you confirm if you actually have the issue with notes? They seem to behave correctly on my side

You are right: only the sources are affected. Apologies for the confusion.
